### ISSUE TITLE
Sample code to initialize the scanner with this library

### ISSUE THREAD

**Issue by TheRobBrennan** [BlueFletch/cordova-plugin-honeywell-captuvo#1]
Hi there! Do you have an example of how to initialize the scanner before using the callback examples in the readme documentation? I see references to "NOTE: You must register a callback to initialize the hardware." but no example for that. 

Thanks!

**Comment by blakebyrnes** [comment]
The example in the readme should be all you need.  Let me know if you've seen those and still aren't sure what to do.

**Comment by TheRobBrennan** [comment]
Hi Blake,

Thanks for your prompt reply! The part I’m confused on is this example:

document.addEventListener("deviceready", function(){ 
       ...
       captuvo.registerScannerCallback(function(barcode){

```
       console.log("Barcode scanned: " + barcode);

       //TODO: handle barcode/label type
   });
   //This function will send the first readable track
   captuvo.registerMagstripeCallback(function(track){
        //track 1 uses carets as dividers (NOTE: won't work if track 2 is read)
        if (track.indexOf("%B") == 0) {
          track = track.split('^');

          var cc = {
             number : track[0].substr(2), //strip leading %B
             name : track[1].trim(),
             expr : '20' + track[2].substr(0,2) + '-' + track[2].substr(2,2)
          };
        } else {
          //handle track 2
        }

   });
```

Where does the device itself - captuvo - get defined/initialized? I’m curious where that part of the code is.

**Comment by blakebyrnes** [comment]
Hi Rob,
When you call captivo.registerScannerCallback, it will activate the hardware under the covers. You should not need to do anything else. Hope that answers your question!
Blake

**Comment by TheRobBrennan** [comment]
Oh yeah. For some reason I was thinking that there was an initialization phase that had to occur.

One final question (I promise) - were you able to get the callback to fire more than once? In a very simple app, I was able to get the callback to fire once, but it failed to run on subsequent scans of the same barcode. Any idea what I might be missing perhaps?

I really do appreciate your time on this. I love the plug-in; just want to make sure I'm using it correctly =)

<pre><code>
document.addEventListener("deviceready", init, false);
var resultDiv;
function init() {
    resultDiv = document.querySelector("#results");
    // Honeywell SL42 scanner
    captuvo.registerScannerCallback(function(barcode){
        //console.log("Barcode scanned: " + barcode);
        resultDiv.innerHTML = "Barcode scanned: " + barcode;
        //TODO: handle barcode/label type
    });
}
</code></pre>

**Comment by TheRobBrennan** [comment]
Solved! Figured it was best to just create a function and have it re-register for the callback:

<pre><code>
document.addEventListener("deviceready", init, false);
var resultDiv;
var counter = 0;
function init() {
    resultDiv = document.querySelector("#results");
    prepareScannerToReceiveBarcodeData();
}
// Honeywell SL42
function prepareScannerToReceiveBarcodeData(){
    captuvo.registerScannerCallback(function(barcode){
        resultDiv.innerHTML = "Barcode scanned [" + counter + "]: " + barcode;
        counter++;    // ...just to prove that we're successfully calling back our function multiple times
        
        // TODO: handle barcode/label type
        /* Super secret processing */
        // Add the callback handler again
        prepareScannerToReceiveBarcodeData();
    }); 
}
</code></pre>
